# fly.toml app configuration file generated for vis3d on 2025-06-11T23:13:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vis3d'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
